create table
  public.tasks (
    id bigint generated by default as identity not null,
    author_id uuid not null,
    title text not null,
    completed boolean not null default false,
    description text null,
    constraint tasks_pkey primary key (id),
    constraint tasks_id_key unique (id),
    constraint tasks_author_id_fkey foreign key (author_id) references auth.users (id) on delete cascade
  ) tablespace pg_default;
